language: java
sudo: false
notifications:
  slack:
    secure: pLj08NFHUKqpXWGs7GS3IV42RtpIBMxwt0XpMlnwWd4FE74XMzKMVxeSG6zhMb53FN1vyroyH+sro6wNJeXyd7WCJ+1oRH97aY2Pc0S3qWebxYW5DeGdl6rQEC2mKHe2ENjOIxHQRDdLQ0XwxuwhzhwErw/mCv4baMKr1FlpXYyvEVqjNSbVKsT+E6OJlbD5gORbfFcQ+6ml9m8RUIZUc2kqNGBhcKVth6FYgAz1sFBvXD7HetjWdpJHPltDJFn2FdgRQmF4op7j1dpIVMsnoDaouTSQEypi+83ZFhY3mi0vYOaR4864lPjF1DpCgV4k1XSDVAjQtdjHvaqBTL2kxnb6DBduWk4SWYeir7RtCt0VSJS0iqS0zbJOVgg3AjOoi5PBIzUTRo3nYmh4/pH4cqDdsOS/qJwtgbtdeBJVJfXA5YoThNi3m32ifBr6MARcBpkawBi2SrMAIKhwvYJxV6lZgrlDOe/5Bwoe67rMTFTPjK0deZWX2JV4K2UD7VPPCfJOLYYfKhnBx8Rxk3tzG/LEsmcXSEBoUuzBMd/ET5xh8g/GBzzJ+VeSn4utgVi/wLmuXaanvAFMJ0ZJTg0GW7f4MNttGIUQSwdNeZtFxe356nrr+kyQVGJngdr7d+Psh4wyeQDBzdNzJrQYpadSoUWrcBTvhYKLBXJRZ83vhYs=
deploy:
  provider: releases
  api_key:
    secure: Rp/oWduOqQ88OWfv1wBUsrpE4G625UiqVXZm2J/Ecd0Ol9TSZcOz15yT3fz/+9/X+i48S9aXUQQ5zH3tAmYFn2xyvMxQaXFX6JSPaR6KipKBR4AxaVTofgY6pvzD6qCG9ZXy/l1YHLXBsQWkIDJo4HV/TYLUSF83N+PGBn8aO7GYHiHr1REEQt1AjT/slMSZuI1VQM/nTA0RU/m3N5BQwtJ3m5K3zvZdEEeS0RqDV9Wn+uJo2CJc8ZL/aSt6J6x8lmPrylhsLbqlY2w+0Dga+8RXXMrRGh0Q5i0PEtGaE44wC0lhvVe11Mg3WPcBx86AAnIoI18lqreyLsYtq6AcKdeP986Z86gtGdu3/tAmMrgknX4hHNt46dqa8HwyEon00f97+qADIlcoGSLiivLZ8Rg0ZZ2I1e9wUihw02WmHvxr56mS/c328vgKj9x/eo3FyuRdrZ9l2pVCRTzCgQPPe7lMqyKWzZoZ3zdTL73yLWa31r5nGnxJbN4vViZavYG4ZRV5eK8upxRhjRrUIAGFS5xOm5BQcxUQsGKUVAKw0dK7npoQZJx9kWl3ZVrq+aenWJ4Tb9LcfZHInswYhXFXyz6fLaSY6Ld8o7lWX9t61MvUPPEMvAK6AZczYuOGFqway+ERKjidHo0GS1VMGhxyxC/iEJADZe0KCbAe+SAb8eo=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-jira-extension-plugin
