language: java
sudo: false
notifications:
  slack:
    secure: pLj08NFHUKqpXWGs7GS3IV42RtpIBMxwt0XpMlnwWd4FE74XMzKMVxeSG6zhMb53FN1vyroyH+sro6wNJeXyd7WCJ+1oRH97aY2Pc0S3qWebxYW5DeGdl6rQEC2mKHe2ENjOIxHQRDdLQ0XwxuwhzhwErw/mCv4baMKr1FlpXYyvEVqjNSbVKsT+E6OJlbD5gORbfFcQ+6ml9m8RUIZUc2kqNGBhcKVth6FYgAz1sFBvXD7HetjWdpJHPltDJFn2FdgRQmF4op7j1dpIVMsnoDaouTSQEypi+83ZFhY3mi0vYOaR4864lPjF1DpCgV4k1XSDVAjQtdjHvaqBTL2kxnb6DBduWk4SWYeir7RtCt0VSJS0iqS0zbJOVgg3AjOoi5PBIzUTRo3nYmh4/pH4cqDdsOS/qJwtgbtdeBJVJfXA5YoThNi3m32ifBr6MARcBpkawBi2SrMAIKhwvYJxV6lZgrlDOe/5Bwoe67rMTFTPjK0deZWX2JV4K2UD7VPPCfJOLYYfKhnBx8Rxk3tzG/LEsmcXSEBoUuzBMd/ET5xh8g/GBzzJ+VeSn4utgVi/wLmuXaanvAFMJ0ZJTg0GW7f4MNttGIUQSwdNeZtFxe356nrr+kyQVGJngdr7d+Psh4wyeQDBzdNzJrQYpadSoUWrcBTvhYKLBXJRZ83vhYs=
deploy:
  provider: releases
  api_key:
    secure: PbV0FWLLpV+pYs9fjqlgoBuWjMiaShVA3RBRKpEXEyYVsCsGsqpRHdQ34QwSJ8o18eL1WDI7pEaQWsuLJDPKBMLmmOm/40OR6D/bwUUCke7ACLAH9dlCPEUhzpgPgHAQxFZLnMzmOrGMNeGGi/h/fCJ1SJONN4q6YglIvOuK+M1S1WNZ46737nFG+vYTobZdf3reCPabnXlMWCgdnCO2+zP1dAFVXwSPhbMbL9WzZRbO1v4rt5kl7Yhg1PqB7pkQZbYDgbGVIt+5vkNsj5oCLRI5lAaJfjcBNUaXDOoigyK4tjgQ34A+VXY8loz/FkdjKYdK2RJy0MAfHx5TukfKOyZqM4HPGAoNzgiUpvehxmje27fSfAjriAa5CKfcXxMDxL6w+PQ2gyFuhYQYAPU68PTa1bVeL+OXB5I92Fiiyqj+OG3FD5tQJN83tqBeNRn5ksFDIC99w+d9K+mix5wZ+HLKyQBG1PFHjX0G+aSP0pRdQS9RjwNa8JRH5kK3BRFjOuWl3iqqqixVqa3RMoDKizoq9xkp4Gqa2rr9InQCHZnQiBhJ8VcTcKQ+VK0YH9YIiBf+/NyLyS63FKChTkaabAXTgwo+bZjb2avOV3f29ENk3azOTKf1r9TwDaK3mdlmlnqx8ywimTMNXuLdch0Z6m56Skwvywizgieg0jpnLzM=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-jira-extension-plugin
